### ISSUE TITLE
%cdk deploy  throws Lambda error

### ISSUE THREAD

**Issue by vksundar** [aws-samples/amazon-textract-serverless-large-scale-document-processing#47]
How to resolve this error:

"Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [10].."

eployment failed: Error: Stack Deployments Failed: Error: The stack named TextractPipelineStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [10]. (Service: Lambda, Status Code: 400, Request ID: 5f7e1ea1-2530-451a-8a45-77ffbe62576c)" (RequestToken: f029c2a0-bf46-806e-adf0-8afb28978446, HandlerErrorCode: InvalidRequest)
    at deployStacks (/home/ec2-user/.nvm/versions/node/v16.18.1/lib/node_modules/cdk/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/home/ec2-user/.nvm/versions/node/v16.18.1/lib/node_modules/cdk/node_modules/aws-cdk/lib/cdk-toolkit.ts:315:7)
    at initCommandLine (/home/ec2-user/.nvm/versions/node/v16.18.1/lib/node_modules/cdk/node_modules/aws-cdk/lib/cli.ts:358:12)

Stack Deployments Failed: Error: The stack named TextractPipelineStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [10]. (Service: Lambda, Status Code: 400, Request ID: 5f7e1ea1-2530-451a-8a45-77ffbe62576c)" (RequestToken: f029c2a0-bf46-806e-adf0-8afb28978446, HandlerErrorCode: InvalidRequest)

**Comment by dannellyz** [comment]
I'm getting this same error. Did you end up finding a resolution?

**Comment by fergfamster** [comment]
You need to open a service Quota increase for your account to something like 500 or higher for Lambda Concurrent executions. Go to Console --> Quota service --> Lambda --> Concurrent Executions --> request 500 or higher
